version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
    ports:
      - 8125:8125
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'better/datadog-stats']
    volumes:
      - ".:/plugin:ro"
